"""empty message

Revision ID: 33d821edb34e
Revises: 
Create Date: 2022-10-24 17:48:19.776588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d821edb34e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r')
    op.add_column('question', sa.Column('body', sa.String(), nullable=False))
    op.add_column('question', sa.Column('tag', sa.String(length=150), nullable=True))
    op.add_column('question', sa.Column('time_stamp', sa.String(length=80), nullable=True))
    op.add_column('question', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('question', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_constraint('question_password_key', 'question', type_='unique')
    op.drop_constraint('question_title_key', 'question', type_='unique')
    op.create_unique_constraint(None, 'question', ['body'])
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'])
    op.drop_column('question', 'first_name')
    op.drop_column('question', 'password')
    op.drop_column('question', 'last_name')
    op.drop_column('question', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('question', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('question', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='unique')
    op.create_unique_constraint('question_title_key', 'question', ['title'])
    op.create_unique_constraint('question_password_key', 'question', ['password'])
    op.alter_column('question', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('question', 'user_id')
    op.drop_column('question', 'time_stamp')
    op.drop_column('question', 'tag')
    op.drop_column('question', 'body')
    op.create_table('r',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='r_pkey'),
    sa.UniqueConstraint('password', name='r_password_key'),
    sa.UniqueConstraint('username', name='r_username_key')
    )
    # ### end Alembic commands ###
