"""empty message

Revision ID: 6f83250b8cbc
Revises: 33d821edb34e
Create Date: 2022-10-24 22:36:46.475362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f83250b8cbc'
down_revision = '33d821edb34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_on', sa.String(length=80), nullable=True))
    op.drop_column('question', 'time_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('time_stamp', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('question', 'created_on')
    # ### end Alembic commands ###
