"""empty message

Revision ID: 82ec864f35af
Revises: 6f83250b8cbc
Create Date: 2022-10-31 14:04:59.262700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ec864f35af'
down_revision = '6f83250b8cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_body_key', 'answer', type_='unique')
    op.drop_constraint('answer_user_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.drop_column('answer', 'user_id')
    op.drop_column('answer', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('tag', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_user_id_fkey', 'answer', 'user', ['user_id'], ['id'])
    op.create_unique_constraint('answer_body_key', 'answer', ['body'])
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
